### ISSUE TITLE
Hex dependency resolution failed

### ISSUE THREAD

**Issue by programisti** [chrismccord/phoenix_haml#12]
Trying to add phoenix_haml into my phoenix project as mentioned on readme, but i get error message. sadly i have no an idea what it's trying to tell me.

added this in my mix.esx:
>{:phoenix_haml, "~> 0.0.5"}

and this one into config/config.ex

>config :phoenix, :template_engines,
    haml: PhoenixHaml.Engine

after executing mix deps.get following message comes:

>Running dependency resolution
Looking up alternatives for conflicting requirements on phoenix
  Activated version: 0.13.1
  From phoenix_haml v0.0.5: ~> 0.4.0
  From mix.exs: ~> 0.13.1
** (Mix) Hex dependency resolution failed, relax the version requirements or unlock dependencies

when i add phoenix_haml via github in mix.esx: 
>{:phoenix_haml, github: "chrismccord/phoenix_haml"}

then it throws same message but with different versions:

>Running dependency resolution
Looking up alternatives for conflicting requirements on phoenix
  Activated version: 0.13.1
  From deps/phoenix_haml/mix.exs: ~> 0.12.0
  From mix.exs: ~> 0.13.1
** (Mix) Hex dependency resolution failed, relax the version requirements or unlock dependencies

What Im doing wrong?

**Comment by chrismccord** [comment]
I need to bump the phoenix dep , but you can try 


    {:phoenix_haml, github: "chrismccord/phoenix_haml", override: true}

**Comment by programisti** [comment]
thank your Chris but same message

>➜  blog  mix deps.get
* Updating phoenix_haml (git://github.com/chrismccord/phoenix_haml.git)
Running dependency resolution
Looking up alternatives for conflicting requirements on phoenix
  Activated version: 0.13.1
  From deps/phoenix_haml/mix.exs: ~> 0.12.0
  From mix.exs: ~> 0.13.1
** (Mix) Hex dependency resolution failed, relax the version requirements or unlock dependencies

Ive also tried to add calliope in my mix.exs but with no results. 
can you explain why this message comes?

here are all of my deps:
>defp deps do             
  [{:phoenix, "~> 0.13.1"},
 {:phoenix_ecto, "~> 0.4"},
 {:postgrex, ">= 0.0.0"},
  {:phoenix_html, "~> 1.0"},
   {:phoenix_live_reload, "~> 0.4", only: :dev},
   {:cowboy, "~> 1.0"},
   {:phoenix_haml, github: "chrismccord/phoenix_haml", override: true},
   {:comeonin, "~> 0.10"}]
 end

**Comment by chrismccord** [comment]
It's being caused by me locking phoenix at 0.12. I need to release a new version that supports >= 0.13

**Comment by programisti** [comment]
ok.
if i will fork it then edit this file 
https://github.com/chrismccord/phoenix_haml/blob/master/mix.exs
and if i will change third line
>defp deps do
    [
      {:phoenix, "~> 0.12.0"},
      {:cowboy, "~> 1.0.0", only: [:dev, :test]},
      {:calliope, "~> 0.3.0"}
    ]
  end

to

>defp deps do
    [
      {:phoenix, "~> 0.13.1"},
      {:cowboy, "~> 1.0.0", only: [:dev, :test]},
      {:calliope, "~> 0.3.0"}
    ]
  end

it will work right?

**Comment by programisti** [comment]
i have fixed by forking this repo and made it friendly with 0.13.1 version of phoenix

if you get similar error fix so: 
change "chrismccord" to "programisti" 
{:phoenix_haml, github: "programisti/phoenix_haml"}

**Comment by chrismccord** [comment]
Can you send a PR?

**Comment by programisti** [comment]
sorry but dont know what PR abbreviation means. 
only PR i know is marketing stuff.

**Comment by chrismccord** [comment]
hehe "Pull request". When you visit this projects page it should present you with an option to "compare and pull request" from your fork.

**Comment by programisti** [comment]
i hope you are looking for this:
https://github.com/chrismccord/phoenix_haml/pull/13

**Comment by programisti** [comment]
fixed.
so you dont need to change author name as i said before.
