### ISSUE TITLE
Feature Proposal: Add mix task to replace eex layout with a haml layout

### ISSUE THREAD

**Issue by smpallen99** [chrismccord/phoenix_haml#33]
I'm proposing that we add a mix task to replace the eex layout file with a haml version. If you agree that this feature belongs here in phoenix_haml, then I'll create a pull request.

**Comment by chrismccord** [comment]
@smpallen99 You have commit access now so feel free to implement this feature :) . What email should I add as a hex collaborator so you can manage releases?

**Comment by smpallen99** [comment]
smpallen99 at yahoo dot com
