### ISSUE TITLE
_build/dev/lib/phoenix/priv/templates/phoenix.gen.html/controller_test.exs:37: undefined function sample_id/0

### ISSUE THREAD

**Issue by jrissler** [chrismccord/phoenix_haml#37]
New to phoenix, generated basic app + added deps and ran:

mix phoenix_haml.gen.html Ticket tickets summary:string description:text issuetype:string
- creating web/controllers/ticket_controller.ex
- creating web/views/ticket_view.ex
  *\* (CompileError) _build/dev/lib/phoenix/priv/templates/phoenix.gen.html/controller_test.exs:37: undefined function sample_id/0
  (elixir) expanding macro: Kernel.<>/2
  _build/dev/lib/phoenix/priv/templates/phoenix.gen.html/controller_test.exs:1: (file)
  (elixir) expanding macro: Kernel.<>/2
  _build/dev/lib/phoenix/priv/templates/phoenix.gen.html/controller_test.exs:1: (file)
  (elixir) expanding macro: Kernel.<>/2
  _build/dev/lib/phoenix/priv/templates/phoenix.gen.html/controller_test.exs:1: (file)
  (elixir) expanding macro: Kernel.<>/2
  _build/dev/lib/phoenix/priv/templates/phoenix.gen.html/controller_test.exs:1: (file)

**Comment by wdiechmann** [comment]
@nixkid - I'm afraid it does not make the test go away :/

I added your repo

```
  defp deps do
    [{:phoenix, "~> 1.2.1"},
     {:phoenix_pubsub, "~> 1.0"},
     {:phoenix_ecto, "~> 3.0"},
     {:mariaex, ">= 0.0.0"},
     {:phoenix_html, "~> 2.6"},
     {:phoenix_haml, github: "nixkid/phoenix_haml"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:gettext, "~> 0.11"},
     {:cowboy, "~> 1.0"}]
  end
```

and got this anyway -

```
$ mix phoenix_haml.gen.html User users call_name email password password_hash
* creating web/controllers/user_controller.ex
* creating web/views/user_view.ex
** (CompileError) _build/dev/lib/phoenix/priv/templates/phoenix.gen.html/controller_test.exs:37: undefined function sample_id/0
    (elixir) expanding macro: Kernel.<>/2
    _build/dev/lib/phoenix/priv/templates/phoenix.gen.html/controller_test.exs:1: (file)
    (elixir) expanding macro: Kernel.<>/2
    _build/dev/lib/phoenix/priv/templates/phoenix.gen.html/controller_test.exs:1: (file)
    (elixir) expanding macro: Kernel.<>/2
    _build/dev/lib/phoenix/priv/templates/phoenix.gen.html/controller_test.exs:1: (file)
    (elixir) expanding macro: Kernel.<>/2
    _build/dev/lib/phoenix/priv/templates/phoenix.gen.html/controller_test.exs:1: (file)

```

**Comment by nixkid** [comment]
@wdiechmann  yeah, I didn't make any changes on master branch, so you need to specify working branch like this in your mix.exs file:
```
{:comeonin, github: "nixkid/phoenix_haml", branch: "fix_haml_gen"}
```
It will do the trick.

**Comment by wdiechmann** [comment]
Oh - figures ;)

Thx for a fast reply!

Cheers
Walther

**Comment by jrissler** [comment]
@nixkid thanks!

**Comment by rchervin** [comment]
I had this same problem too @nixkid thank you for the fix!
