### ISSUE TITLE
phoenix_haml and phoenix v0.11.0

### ISSUE THREAD

**Issue by NobbZ** [chrismccord/phoenix_haml#8]
Hi there!

Current version of phoenix is 0.11.0, phoenix_haml can't be used with that.

**Comment by chrismccord** [comment]
I won't have time to get to this for a bit, can you attach a PR? We should simply be able to bump the phoenix version

**Comment by NobbZ** [comment]
I will give it a try with a local fork this evening and do a PR if it works.
